name: medb_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  flutter_secure_storage: ^9.2.4
  go_router: ^16.2.0
  provider: ^6.1.5+1
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1  

flutter_launcher_icons:             
  android: true
  ios: true
  image_path: "assets/medbsmalllogo.png"    

flutter:
  uses-material-design: true
  assets:
    - assets/medb.png
    - assets/medbsmalllogo.png
